### ISSUE TITLE
Allow customization of script name.

### ISSUE THREAD

**Issue by kentcdodds** [bahmutov/dont-break#24]
I have a use case where I have a project that uses my module that runs basic unit tests for `npm test` and then a full suite for `npm run test:all`. I'd rather run the full suite of tests in my `dont-break`.

**Comment by bahmutov** [comment]
Try dont-break@0.3.3 with custom commands. In the `.dont-break` file just put a custom command for each dependent project after `:` for example
```
foo: gulp test
bar: make
// use default "npm test" for baz
baz
```

**Comment by kentcdodds** [comment]
Ah, perfect. Thanks!
