### ISSUE TITLE
Allow specifying the install timeout

### ISSUE THREAD

**Issue by nolanlawson** [bahmutov/dont-break#26]
`pouchdb` takes a long time to `npm install` due to a leveldown dependency. If any install takes more than 10 seconds, `dont-break` will throw an error.

I really want to use this module, because we have a huge problem in pouchdb with testing dependencies (lots of `npm link` and `ln -s`; it's ugly). But maybe there should be some way to increase the timeout?

Here's the log:

```
dont-break@0.3.3 - Checks if the current version of your package would break dependent projects
in folder /home/nolan/workspace/pouchdb-server
testing dependents
pouchdb: test-node
testing "pouchdb: test-node"
testing folder "/tmp/pouchdb-server@0.6.6-against-pouchdb"
  installing pouchdb
npm WARN peerDependencies The peer dependency bn.js@^0.15.0 included from miller-rabin will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
FAIL: Current version breaks dependents
REPORTED ERROR: install timed out for pouchdb
Error: install timed out for pouchdb
    at Promise_timeout_task [as _onTimeout] (/home/nolan/workspace/pouchdb-server/node_modules/dont-break/node_modules/q/q.js:1070:25)
    at Timer.listOnTimeout (timers.js:89:15)
restored folder /home/nolan/workspace/pouchdb-server
finishing with success? false
```

**Comment by gr2m** [comment]
I just run into the same issue. Would you mind a PR that checks for a `DONT_BREAK_INSTALL_TIMEOUT` env variable, or something similar?

**Comment by bahmutov** [comment]
Almost done, trying to setup end to end testing for this project before releasing, https://github.com/bahmutov/dont-break/issues/30

**Comment by bahmutov** [comment]
Seems `--timeout N` where N is in seconds is working

**Comment by gr2m** [comment]
thanks :+1:
