### ISSUE TITLE
Fetch top dependent projects automatically 

### ISSUE THREAD

**Issue by bahmutov** [bahmutov/dont-break#6]
If user has option `--top 5` find 5 most popular NPM projects that depend on your package instead of .dont-break file

Post to https://github.com/npm/npm/issues/6510 when done

**Comment by jaridmargolin** [comment]
Curious why a separate dotfile is required rather than just utilizing a prop in package.json. Seems like this was an intentional decision?

**Comment by bahmutov** [comment]
Separate file was simpler to use because the tool can grab dependent projects and save it. I agree with you that it should be additional property in the package json file too.
