### ISSUE TITLE
config repo url & test command

### ISSUE THREAD

**Issue by Aladdin-ADD** [bahmutov/dont-break#72]
https://github.com/bahmutov/dont-break#test-command

is there a way to config like this:
```js
// .dont-break.json
[
  {
    "url": "https://github.com/bahmutov/dont-break",  // or similar field
    "test": "npm test"
  }
]
```

**Comment by artemv** [comment]
@Aladdin-ADD yes, just use `name` instead of `url` in your example (`url` would be better, agreed), and it will work.
